vcenter:
  ip: 10.0.0.10
  admin_username: administrator@vsphere.local
  admin_password: Password1!
  datacenter: dc0
  cluster: LAB
  datastore: ds0
  network: 10.0.0.x-24
  folder: openshift4
  create_folder: True
openshift:
  vcenter_svc_account: OCP4Admin@vsphere.local
  installer_created_folder: False
